name: scalex_chatbot
description: AI-Powered Mobile Chatbot with multiple AI models support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3

  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Internationalization
  easy_localization: ^3.0.3

  # UI Components
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  uuid: ^4.2.2

  # PDF Export
  pdf: ^3.10.7
  printing: ^5.11.1

  # Speech to Text (Bonus)
  speech_to_text: ^6.5.1

  # Permissions
  permission_handler: ^11.1.0

  # Environment Variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  share_plus: ^7.0.1
  path_provider: ^2.1.1
  pdf: ^3.10.4
  printing: ^5.11.2
  speech_to_text: ^6.6.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - .env

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
        - asset: assets/fonts/DejaVuSans.ttf
        - asset: assets/fonts/DejaVuSans-Bold.ttf
          weight: 700